FROM xxx/spark:v3.3

USER root
RUN set -ex && \
    mkdir -p /opt/spark/listeners && \
    mkdir -p /opt/spark/listeners/lib
COPY target/scala-2.12/sparkeventlistener4measure_2.12-0.0.1.jar /opt/spark/listeners
COPY docker/lib /opt/spark/listeners/lib
